# -*- coding: utf-8 -*-
"""Armstrong Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1xvQYP4Ak0kyr3XlVUyEQ2XnEtStIQI
"""

import streamlit as st
import math

def is_armstrong_number(number):
    numlength = 1
    armstrongsum = 0
    calcnumb = number
    while calcnumb >= 10:
        numlength = numlength + 1
        calcnumb = calcnumb/10
    counter = numlength
    while counter > 0:
        armstrongsum = armstrongsum + math.trunc(calcnumb)**numlength
        calcnumb = round(calcnumb*10 - math.trunc(calcnumb)*10, numlength)
        counter = counter - 1
    if armstrongsum == number:
        return True
    return False

st.title("Armstrong Number Program")
number_string=" "
while not number_string.isdigit():
  number_string = st.text_input("Enter a number: ")
if is_armstrong_number(number):
    st.write(str(number) + " is an Armstrong number")
else:
    st.write(str(number) + " is not an Armstrong number")